theme: minima
repository: diegocarvajal98.github.io
title: Diego's personal website
author: Diego A. Carvajal S., BSc.
email: diego98cs _AT_ gmail.com

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

#markdown: kramdown

markdown_extensions:
  - attr_list

header_pages:
  - lnktr.md
  - index.md
  - projects/index.md
  - press.md

github_username: DiegoCarvajal98
linkedin_username: diegocarvajal98