site_name: Diego Carvajal - Robotics
site_url: https://DiegoCarvajal98.github.io/diegocarvajal98.github.io
nav:
  - About: index.md
  - Projects: projects.md
theme:
  name: material
  favicon: images/favicon.svg
  logo: images/logo.png
  language: en
  palette: 
    primary: custom
    accent: blue grey
  # custom_dir: overrides
# extra_css:
#   - stylesheets/extra.css
