site_name: Diego Carvajal - Robotics
site_url: https://DiegoCarvajal98.github.io/
nav:
  - About: index.md
  - Media: media.md
  - Projects: projects.md
theme:
  name: material
  favicon: images/favicon.svg
  logo: images/logo.png
  language: en
  palette: 
    primary: blue
    accent: blue
  # custom_dir: overrides

plugins:
  - open-in-new-tab
  # - macros:
  #     module_name: main
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.blocks.html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: /fontawesome/solid/envelope
      name: Send Diego an enquiry by mail
      link: mailto:diego98cs%40gmail.com
    - icon: fontawesome/brands/linkedin
      name: Diego on LinkedIn
      link: https://www.linkedin.com/in/dcarvajal98/
    - icon: fontawesome/brands/github
      name: Diego on Github
      link: https://github.com/DiegoCarvajal98
    - icon: fontawesome/brands/google-scholar
      name: Diego on Google Scholar
      link: https://scholar.google.com/citations?user=hrbTkhgAAAAJ&hl=en
    - icon: fontawesome/brands/youtube
      name: Diego on Youtube
      link: https://www.youtube.com/channel/UCcz0JL8eeMNP4KG7p_mTfJA